# Uses https://github.com/marketplace/actions/changed-files

name: Isolated Migrations

on:
  pull_request

jobs:
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  # Event `pull_request`: Compare the last commit of the main branch or last remote commit of the PR branch -> to the current commit of a PR branch.
  # ------------------------------------------------------------------------------------------------------------------------------------------------
  changed_files:
    runs-on: ubuntu-latest
    name: Check for Isolated Migrations
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: A - Group files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v39
        with:
          files_yaml: |
            db:
              - db/**
            non_db:
              - '!db/**'
            schema_migrations:
              - db/migrate/**
            data_migrations:
              - db/data/**
            schema:
              - db/schema.rb
            data_schema:
              - db/data_schema.rb

      - name: B - List the files related to migrations that this PR changes
        if: steps.changed-files-yaml.outputs.db_any_changed == 'true'
        run: |
          echo "Related to migrations:"
          for file in ${{ steps.changed-files-yaml.outputs.db_all_changed_files }}; do
            echo "- $file"
          done

      - name: C - List the files not related to migrations that this PR changes
        if: steps.changed-files-yaml.outputs.non_db_any_changed == 'true'
        run: |
          echo "Not related to migrations:"
          for file in ${{ steps.changed-files-yaml.outputs.non_db_all_changed_files }}; do
            echo "- $file"
          done

      - name: D - Check if the Pull Request contains code changes together with migrations
        if: (steps.changed-files-yaml.outputs.db_any_changed == 'true') && (steps.changed-files-yaml.outputs.non_db_all_changed_files_count > 0)
        run: |
          echo "There are code changes together with migrations. Please split them into two Pull Requests"
          exit 1

      - name: E - Do not miss schema changes
        if: (steps.changed-files-yaml.outputs.schema_migrations_any_changed == 'true') && (steps.changed-files-yaml.outputs.schema_any_changed == 'false')
        run: |
          echo "You introduced some schema migration, please introduce the schema.rb changes as well"
          exit 1

      - name: F - Do not miss data schema changes
        if: (steps.changed-files-yaml.outputs.schema_data_migrations_any_changed == 'true') && (steps.changed-files-yaml.outputs.data_schema_any_changed == 'false')
        run: |
          echo "You introduced some data migrations, please introduce the data_schema.rb changes as well"
          exit 1

