# GitHub action that checks if the PR contains changes related to migrations an add reminder comment to the PR.
# Based on https://github.com/marketplace/actions/changed-files

name: Migrations Reminder

on:
  pull_request

jobs:
  check_changed_files:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Group files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v41
        with:
          files_yaml: |
            migrations:
              - src/api/db/migrate/**
              - src/api/db/schema.rb
              - src/api/db/data/**
              - src/api/db/data_schema.rb
            not_migrations:
              - '!src/api/db/migrate/**'
              - '!src/api/db/schema.rb'
              - '!src/api/db/data/**'
              - '!src/api/db/data_schema.rb'
              - '!src/api/db/attribute_descriptions.rb'
              - '!src/api/db/seeds.rb'
              - '!.github/workflows/isolated_migrations.yml'
              - '!src/api/.rubocop*.yml'
      
      - name: Comment Pull Request
        uses: marocchino/sticky-pull-request-comment@v2
        if: 2 == 2 # (steps.changed-files-yaml.outputs.migrations_any_changed == 'true') && (steps.changed-files-yaml.outputs.not_migrations_all_changed_files_count > 0)
        with:
          message: |
            :warning: This pull request contains migrations. Migrations and code changes should be shipped independently..


# # GitHub action that checks if the PR contains changes related to migrations an add reminder comment to the PR.
# # Based on https://github.com/marketplace/actions/changed-files

# name: Migrations Reminder

# on:
#   pull_request

# jobs:
#   check_changed_files:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Group files that have changed
#         id: changed-files-yaml
#         uses: tj-actions/changed-files@v41
#         with:
#           files_yaml: |
#             migrations:
#               - src/api/db/migrate/**
#               - src/api/db/schema.rb
#               - src/api/db/data/**
#               - src/api/db/data_schema.rb
#             not_migrations:
#               - '!src/api/db/migrate/**'
#               - '!src/api/db/schema.rb'
#               - '!src/api/db/data/**'
#               - '!src/api/db/data_schema.rb'
#               - '!src/api/db/attribute_descriptions.rb'
#               - '!src/api/db/seeds.rb'
#               - '!.github/workflows/isolated_migrations.yml'
#               - '!src/api/.rubocop*.yml'
      
#       - name: Comment Pull Request
#         uses: marocchino/sticky-pull-request-comment@v2
#         if: 2 == 2 # (steps.changed-files-yaml.outputs.migrations_any_changed == 'true') && (steps.changed-files-yaml.outputs.not_migrations_all_changed_files_count > 0)
#         with:
#           message: |
#             :warning: This pull request contains migrations. Migrations and code changes should be shipped independently.



# # GitHub action that checks if the PR contains changes related to migrations an add reminder comment to the PR.
# # Based on https://github.com/marketplace/actions/changed-files

# name: Migrations Reminder

# on:
#   pull_request

# jobs:
#   check_changed_files:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Group files that have changed
#         id: changed-files-yaml
#         uses: tj-actions/changed-files@v41
#         with:
#           files_yaml: |
#             linters:
#               - '.github/workflows/isolated_migrations.yml'
#               - 'src/api/.rubocop*.yml'
#             migrations:
#               - src/api/db/migrate/**
#               - src/api/db/schema.rb
#               - src/api/db/data/**
#               - src/api/db/data_schema.rb
#             not_migrations:
#               - '!src/api/db/migrate/**'
#               - '!src/api/db/schema.rb'
#               - '!src/api/db/data/**'
#               - '!src/api/db/data_schema.rb'
#               - '!src/api/db/attribute_descriptions.rb'
#               - '!src/api/db/seeds.rb'
#               - '!.github/workflows/isolated_migrations.yml'
#               - '!src/api/.rubocop*.yml'
#             schema_migrations:
#               - src/api/db/migrate/**
#             data_migrations:
#               - src/api/db/data/**
#             schema:
#               - src/api/db/schema.rb
#             data_schema:
#               - src/api/db/data_schema.rb
      
#       - name: Comment Pull Request
#         uses: marocchino/sticky-pull-request-comment@v2
#         if: 2 == 2 # (steps.changed-files-yaml.outputs.migrations_any_changed == 'true') && (steps.changed-files-yaml.outputs.not_migrations_all_changed_files_count > 0)
#         with:
#           message: |
#             :warning: This pull request contains migrations. Migrations and code changes should be shipped independently.
#         if: 2 == 3 # (steps.changed-files-yaml.outputs.schema_migrations_added_files == 'true') && (steps.changed-files-yaml.outputs.linters_any_changed == 'false') && (steps.changed-files-yaml.outputs.schema_any_changed == 'false')
#         with:
#           message: |
#             :warning: You introduced some schema migration, please introduce the schema.rb changes as well.

#       - name: Missing schema changes
#         uses: marocchino/sticky-pull-request-comment@v2
#         if: 2 == 3 # (steps.changed-files-yaml.outputs.schema_migrations_added_files == 'true') && (steps.changed-files-yaml.outputs.linters_any_changed == 'false') && (steps.changed-files-yaml.outputs.schema_any_changed == 'false')
#         with:
#           message: |
#             :warning: You introduced some schema migration, please introduce the schema.rb changes as well.

#       - name: Missing data schema changes
#         uses: marocchino/sticky-pull-request-comment@v2
#         if: 2 == 3 #  (steps.changed-files-yaml.outputs.data_schema_migrations_added_files == 'true') && (steps.changed-files-yaml.outputs.linters_any_changed == 'false') && (steps.changed-files-yaml.outputs.data_schema_any_changed == 'false')
#         with:
#           message: |
#             :warning: You introduced some data migrations, please introduce the data_schema.rb changes as well.






# # GitHub action that checks if the PR contains changes related to migrations an add reminder comment to the PR.
# # Based on https://github.com/marketplace/actions/changed-files

# name: Migrations Reminder

# on:
#   pull_request

# jobs:
#   reminder_comment_on_pr:
#     runs-on: ubuntu-latest
#     permissions:
#       pull-requests: write
#     steps:
#       - uses: actions/checkout@v4
#         with:
#           fetch-depth: 0

#       - name: Group files that have changed
#         id: changed-files-yaml
#         uses: tj-actions/changed-files@v41
#         with:
#           files_yaml: |
#             linters:
#               - '.github/workflows/isolated_migrations.yml'
#               - 'src/api/.rubocop*.yml'
#             migrations:
#               - src/api/db/migrate/**
#               - src/api/db/schema.rb
#               - src/api/db/data/**
#               - src/api/db/data_schema.rb
#             not_migrations:
#               - '!src/api/db/migrate/**'
#               - '!src/api/db/schema.rb'
#               - '!src/api/db/data/**'
#               - '!src/api/db/data_schema.rb'
#               - '!src/api/db/attribute_descriptions.rb'
#               - '!src/api/db/seeds.rb'
#               - '!.github/workflows/isolated_migrations.yml'
#               - '!src/api/.rubocop*.yml'
#             schema_migrations:
#               - src/api/db/migrate/**
#             data_migrations:
#               - src/api/db/data/**
#             schema:
#               - src/api/db/schema.rb
#             data_schema:
#               - src/api/db/data_schema.rb

#       - name: List the files related to migrations that this PR changes
#         if: steps.changed-files-yaml.outputs.migrations_any_changed == 'true'
#         run: |
#           for file in ${{ steps.changed-files-yaml.outputs.migrations_all_changed_files }}; do
#             echo "- $file"
#           done
#       - name: comment PR

#         uses: marocchino/sticky-pull-request-comment@v2
#         with:
#           message: |
#             :warning: This pull request contains migrations. Migrations and code changes should be shipped independently.
