name: Warn that PR contains a migration
on:
  pull_request

permissions:
  contents: write
jobs:
  # TODO: check if there are migrations and warn in the comment.
  comment_on_pr:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Group files that have changed
        id: changed-files-yaml
        uses: tj-actions/changed-files@v42
        with:
          files_yaml: |
            schema_migrations:
              - src/api/db/migrate/**
            data_migrations:
              - src/api/db/data/**
            not_db_schema:
              - src/api/db/schema.rb
            not_data_schema:
              - src/api/db/data_schema.rb
            migrations:
              - src/api/db/migrate/**
              - src/api/db/data/**
            not_migrations:
              - '!src/api/db/migrate/**'
              - '!src/api/db/data/**'
      - name: Check if the Pull Request contains code changes together with migrations
        if: (steps.changed-files-yaml.outputs.migrations_any_changed == 'true') && (steps.changed-files-yaml.outputs.not_migrations_all_changed_files_count > 0)
        run: |
          echo "This PR includes migration"

      - name: 'There is a migration but not its schema'
        # if: ((steps.changed-files-yaml.outputs.schema_migrations_any_changed == 'true') && (steps.changed-files-yaml.outputs.not_db_schema_all_changed_files_count > 0)) || ((steps.changed-files-yaml.outputs.data_migrations_any_changed == 'true') && (steps.changed-files-yaml.outputs.not_data_schema_all_changed_files_count > 0))
        if: (steps.changed-files-yaml.outputs.migrations_any_changed == 'true') && (steps.changed-files-yaml.outputs.not_migrations_all_changed_files_count > 0)
        run: |
          echo "There is a migration but not its schema. Please add it."

      - name: Add Comment to PR
        uses: thollander/actions-comment-pull-request@v2
        if: (steps.changed-files-yaml.outputs.migrations_any_changed == 'true') && (steps.changed-files-yaml.outputs.not_migrations_all_changed_files_count > 0)
        with:
          comment_tag: warn_migration
          message: |
            :warning: Please make sure the migration is shipped in an independent Pull Request. :warning:

            :heavy_check_mark: You can include schema changes, annotations and validations for consistency but :x: avoid committing other changes with it.
